import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#101E17"
    },
    imageContainer: {
        flex: 1.6,
        position: "relative",
        justifyContent: "flex-end",
    },
    bottomContainer: {
        flex: 1,
        paddingHorizontal: 20,
    },
    image: {
        width: "100%",
        height: "100%",
        resizeMode: "stretch",
    },
    closeButton: {
        position: "absolute",
        top: 20,
        right: 20,
        width: 24,
        height: 24,
        borderRadius: "50%",
        backgroundColor: "rgba(0, 0, 0, 0.4)",
        justifyContent: "center",
        alignItems: "center",
    },
    closeButtonText: {
        color: "#FFFFFF",
        fontSize: 10,
        fontWeight: 500,
    },
    featureList: {
        paddingBottom: 20,
    },
    featureContainer: {
        position: "absolute",
        paddingLeft: 20,
    },
    featureTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#FFFFFF",
    },
    featureSubtitle: {
        fontSize: 17,
        color: "rgba(255, 255, 255, 0.7)",
        marginBottom: 20,
        lineHeight: 24,
        letterSpacing: 0.38,
        fontWeight: 200,
    },
    featureCard: {
        backgroundColor: "rgba(0, 0, 0, 0.24)",
        borderRadius: 10,
        padding: 20,
        marginRight: 5,
        justifyContent: "center",
        width: 156,
        height: 130,
    },
    featureCardIconContainer: {
        backgroundColor: "rgba(0,0,0, 0.24)",
        width: 36,
        height: 36,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
    },
    featureCardIcon: {
        width: 18,
        height: 18,
    },
    featureCardTitle: {
        fontSize: 20,
        fontWeight: 500,
        color: "#FFFFFF",
        letterSpacing: 0.38,
        lineHeight: 24,
    },
    featureCardDescription: {
        fontSize: 13,
        color: "rgba(255, 255, 255, 0.7)",
        lineHeight: 18,
        letterSpacing: -0.08,
    },
    subscriptionPlanContainer: {
        paddingVertical: 10,
        gap: 10,
        marginBottom: 10,
    },
    subscriptionPlan: {
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderRadius: 14,
        width: "100%",
        flexDirection: "row",
        borderColor: "rgba(255, 255, 255, 0.3)",
        borderWidth: 0.5,
        height: 60,
        alignItems: "center",
        paddingHorizontal: 20,
        gap: 10,
    },
    subscriptionPlanCheck: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
    },
    subscriptionPlanCheckInner: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#FFFFFF",
    },
    subscriptionPlanTitle: {
        fontSize: 16,
        fontWeight: 500,
        color: "#FFFFFF",
    },
    subscriptionPlanDescription: {
        fontSize: 12,
        color: "rgba(255, 255, 255, 0.7)",
    },
    subscriptionPlanSelected: {
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderColor: "#28AF6E",
        borderWidth: 1.5,
    },
    subscriptionPlanCheckSelected: {
        backgroundColor: "#28AF6E",
        justifyContent: "center",
        alignItems: "center",
    },
    yearlyDiscount: {
        position: "absolute",
        top: 0,
        right: 0,
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderTopRightRadius: 13,
        borderBottomLeftRadius: 24,
        backgroundColor: "#28AF6E",
        fontSize: 12,
        color: "#ffffff",
        fontWeight: 500,
        lineHeight: 18,
    },
    subscriptionPlanWarning: {
        fontSize: 9,
        fontWeight: 200,
        color: "rgba(255, 255, 255, 0.52)",
        textAlign: "center",
        marginTop: 10,
    },
    footer: {
        fontSize: 11,
        color: "rgba(255, 255, 255, 0.52)",
        textAlign: "center",
        marginTop: 10,
    },
});
